#!/usr/bin/env bash
#
# Spawner installer: sets up a server dedicated to preview environments,
# upgrades it, or removes it. Running it again keeps the secrets and the data.
#
#   curl -fsSL https://github.com/Flosk6/Spawner/releases/latest/download/install.sh | sudo bash
#
# Options, each also read from the environment variable in brackets:
#   --domain <domain>      domain of the previews, such as preview.example.com: a DNS
#                          record *.<domain> must point to this server [SPAWNER_DOMAIN]
#   --email <address>      Let's Encrypt account [SPAWNER_EMAIL]
#   --dns-provider <code>  DNS provider for one wildcard certificate: cloudflare, ovh,
#                          hetzner, scaleway, digitalocean, route53, gandiv5, another
#                          lego code, or none for one certificate per host
#                          [SPAWNER_DNS_PROVIDER]
#   --dns-env KEY=VALUE    a credential of the DNS provider, repeatable, such as
#                          CF_DNS_API_TOKEN=... (or set the variable itself)
#   --tls off              plain HTTP: a local install, with --domain localtest.me
#                          [SPAWNER_TLS]
#   --version <version>    version to install or upgrade to, or latest (default: the
#                          version of this installer) [SPAWNER_VERSION]
#   --image <image>        image to run instead of ghcr.io/flosk6/spawner:<version>
#                          [SPAWNER_IMAGE]
#   --zram yes|no          compressed swap, offered below 8 GiB of memory [SPAWNER_ZRAM]
#   --min-disk <GiB>       free disk required (default: 20) [SPAWNER_MIN_DISK_GB]
#   --memory-limit <size>  memory of the Spawner container, such as 1g or 1536m
#                          (default: 1g) [SPAWNER_MEMORY_LIMIT]
#   --yes                  ask nothing, and fail when an answer is missing
#   --upgrade              back the database up, then move to --version
#   --allow-downgrade      install a version older than the one installed (its
#                          database only migrates forward: restore its backup)
#   --uninstall            stop Spawner and its environments; the data stays
#   --purge                with --uninstall, delete the environments and the data too
#
# Files: /opt/spawner (compose.yaml, .env, dns.env, spawner.env,
# firewall.nft, backups/), data in /var/lib/spawner. Docker runs the stack:
# nothing else is installed on the host, apart from Docker itself, nftables
# (the rules of firewall.nft, loaded before Docker by a drop-in of
# docker.service) and zram if asked. spawner.env holds settings of your own,
# which the installer never overwrites. SPAWNER_BOOTSTRAP_TOKEN, when set,
# becomes a token of the installation with every scope, for scripts: none is
# made otherwise.

set -euo pipefail

DEFAULT_VERSION="2.1.0"
# The digest of the image of DEFAULT_VERSION, which the release workflow
# writes into the install.sh it publishes: installing or upgrading to that
# version runs the image the release built, whatever its tag points to later.
IMAGE_DIGEST=""
IMAGE_REPOSITORY="ghcr.io/flosk6/spawner"
# Postgres and Traefik, pinned by digest: bumped by hand before a release
# (scripts/README.md).
POSTGRES_IMAGE="postgres:17-alpine@sha256:b0f9560a2de083e2cc7382e75f808c7381a32852a7ec49117deedb300e552b24"
TRAEFIK_IMAGE="traefik:v3.7@sha256:575fa15b135078fe5e50aa847987d96dbddd7b093c172429618404df73f3fa7c"
RELEASES_API="https://api.github.com/repos/Flosk6/Spawner/releases/latest"
INSTALL_DIR="${SPAWNER_INSTALL_DIR:-/opt/spawner}"
DATA_DIR="${SPAWNER_DATA_DIR:-}"
ENV_FILE="$INSTALL_DIR/.env"
DNS_ENV_FILE="$INSTALL_DIR/dns.env"
SETTINGS_FILE="$INSTALL_DIR/spawner.env"
COMPOSE_FILE="$INSTALL_DIR/compose.yaml"
FIREWALL_FILE="$INSTALL_DIR/firewall.nft"
FIREWALL_DROPIN=/etc/systemd/system/docker.service.d/spawner-firewall.conf
MARKER="# Generated by the Spawner installer"
BACKUPS_KEPT=5

DOMAIN="${SPAWNER_DOMAIN:-}"
EMAIL="${SPAWNER_EMAIL:-}"
DNS_PROVIDER="${SPAWNER_DNS_PROVIDER:-}"
TLS="${SPAWNER_TLS:-}"
VERSION="${SPAWNER_VERSION:-}"
IMAGE="${SPAWNER_IMAGE:-}"
ZRAM="${SPAWNER_ZRAM:-}"
MIN_DISK_GB="${SPAWNER_MIN_DISK_GB:-20}"
MEMORY_LIMIT="${SPAWNER_MEMORY_LIMIT:-}"
ASSUME_YES=false
ACTION=install
PURGE=false
ALLOW_DOWNGRADE=false
BOOTSTRAP_TOKEN="${SPAWNER_BOOTSTRAP_TOKEN:-}"
DNS_VARS=()
declare -A DNS_VALUES=()
DOCKER_INSTALLED_NOW=false
# An upgrade in progress: a failure puts the previous version back (roll_back).
ROLLBACK=false
REPLACED=false
BACKUP_FILE=""

# --- Output -------------------------------------------------------------------

if [ -t 1 ]; then
  BOLD=$'\033[1m' DIM=$'\033[2m' RED=$'\033[31m' GREEN=$'\033[32m' YELLOW=$'\033[33m' RESET=$'\033[0m'
else
  BOLD="" DIM="" RED="" GREEN="" YELLOW="" RESET=""
fi

step() { printf '\n%s== %s%s\n' "$BOLD" "$*" "$RESET"; }
say() { printf '%s\n' "$*"; }
ok() { printf '%sok%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%swarning:%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
die() {
  printf '%serror:%s %s\n' "$RED" "$RESET" "$*" >&2
  [ "$ROLLBACK" != true ] || roll_back
  exit 1
}

usage() {
  cat <<'EOF'
Spawner installer: sets up a server dedicated to preview environments.

  install.sh [--domain preview.example.com] [--email you@example.com]
             [--dns-provider cloudflare|ovh|hetzner|scaleway|digitalocean|route53|gandiv5|<lego code>|none]
             [--dns-env KEY=VALUE]... [--version 2.0.0|latest] [--image IMAGE]
             [--zram yes|no] [--min-disk GiB] [--memory-limit 1g] [--yes]
  install.sh --tls off --domain localtest.me --yes     local install over HTTP
  install.sh --upgrade [--version VERSION]             back the database up, then upgrade
  install.sh --uninstall [--purge]                     stop Spawner (--purge: delete everything)

Without an option, the installer asks what it needs. Documentation:
https://spawner.run/docs/install/
EOF
  exit "${1:-0}"
}

# A question, from the terminal even when the script comes through a pipe.
# ask VARIABLE "Question" [default]
ask() {
  local variable=$1 question=$2 default=${3:-} answer=""
  if [ "$ASSUME_YES" = true ] || [ ! -r /dev/tty ]; then
    [ -n "$default" ] || die "$question: give it with an option (see --help)"
    printf -v "$variable" '%s' "$default"
    return
  fi
  if [ -n "$default" ]; then
    read -r -p "$question [$default]: " answer </dev/tty || true
  else
    read -r -p "$question: " answer </dev/tty || true
  fi
  printf -v "$variable" '%s' "${answer:-$default}"
}

# A secret, such as a token of the DNS provider: not shown while typed.
# ask_secret VARIABLE "Question"
ask_secret() {
  local variable=$1 question=$2 answer=""
  if [ "$ASSUME_YES" = true ] || [ ! -r /dev/tty ]; then
    die "$question: give it with an option (see --help)"
  fi
  read -rs -p "$question (hidden): " answer </dev/tty || true
  printf '\n'
  printf -v "$variable" '%s' "$answer"
}

# A yes or no question; the default applies without a terminal or with --yes.
confirm() {
  local question=$1 default=${2:-n} answer=""
  if [ "$ASSUME_YES" = true ] || [ ! -r /dev/tty ]; then
    [ "$default" = y ]
    return
  fi
  read -r -p "$question [$([ "$default" = y ] && echo Y/n || echo y/N)]: " answer </dev/tty || true
  answer=${answer:-$default}
  [[ "$answer" =~ ^[Yy] ]]
}

# A field of /etc/os-release, read rather than sourced: the file defines
# VERSION, NAME and ID, which would replace the installer's own variables.
os_release() {
  sed -n "s/^$1=//p" /etc/os-release 2>/dev/null | head -1 | tr -d '"'
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# --- Arguments ----------------------------------------------------------------

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --domain) DOMAIN=${2:?--domain needs a value}; shift 2 ;;
      --email) EMAIL=${2:?--email needs a value}; shift 2 ;;
      --dns-provider) DNS_PROVIDER=${2:?--dns-provider needs a value}; shift 2 ;;
      --dns-env) DNS_VARS+=("${2:?--dns-env needs KEY=VALUE}"); shift 2 ;;
      --tls) TLS=${2:?--tls needs a value}; shift 2 ;;
      --version) VERSION=${2:?--version needs a value}; shift 2 ;;
      --image) IMAGE=${2:?--image needs a value}; shift 2 ;;
      --zram) ZRAM=${2:?--zram needs yes or no}; shift 2 ;;
      --min-disk) MIN_DISK_GB=${2:?--min-disk needs a number}; shift 2 ;;
      --memory-limit) MEMORY_LIMIT=${2:?--memory-limit needs a size}; shift 2 ;;
      --yes | -y) ASSUME_YES=true; shift ;;
      --upgrade) ACTION=upgrade; shift ;;
      --uninstall) ACTION=uninstall; shift ;;
      --purge) PURGE=true; shift ;;
      --allow-downgrade) ALLOW_DOWNGRADE=true; shift ;;
      --help | -h) usage 0 ;;
      *) die "unknown option $1 (see --help)" ;;
    esac
  done
  case "${TLS:-letsencrypt}" in
    off | letsencrypt) ;;
    *) die "--tls is off or letsencrypt, not $TLS" ;;
  esac
  [ "$PURGE" = false ] || [ "$ACTION" = uninstall ] || die "--purge goes with --uninstall"
  if [ -n "$MEMORY_LIMIT" ]; then
    [[ "$MEMORY_LIMIT" =~ ^[1-9][0-9]*[mg]$ ]] || die "--memory-limit is a size such as 1g or 1536m, not $MEMORY_LIMIT"
    local mib=${MEMORY_LIMIT%?}
    [ "${MEMORY_LIMIT: -1}" = m ] || mib=$((mib * 1024))
    [ "$mib" -ge 512 ] || die "--memory-limit: Spawner needs 512m at least"
  fi
}

# Values of a previous installation, kept unless an option changes them. The
# .env alone is enough, as on a new server restored from a backup.
load_previous() {
  if [ ! -f "$ENV_FILE" ]; then
    DATA_DIR=${DATA_DIR:-/var/lib/spawner}
    check_directory SPAWNER_DATA_DIR "$DATA_DIR"
    return 0
  fi
  head -1 "$ENV_FILE" | grep -q "^$MARKER" ||
    die "$INSTALL_DIR holds an installation this installer did not make (an older Spawner?): back it up and remove it first"
  local line key value previous_data_dir=""
  while IFS= read -r line || [ -n "$line" ]; do
    [[ "$line" == *=* && "$line" != \#* ]] || continue
    key=${line%%=*}
    value=${line#*=}
    case "$key" in
      SPAWNER_DATA_DIR) previous_data_dir=$value ;;
      SPAWNER_PREVIEW_DOMAIN) DOMAIN=${DOMAIN:-$value} ;;
      ACME_EMAIL) EMAIL=${EMAIL:-$value} ;;
      SPAWNER_DNS_PROVIDER) DNS_PROVIDER=${DNS_PROVIDER:-$value} ;;
      SPAWNER_TLS) TLS=${TLS:-$value} ;;
      SPAWNER_VERSION) PREVIOUS_VERSION=$value ;;
      SPAWNER_IMAGE) PREVIOUS_IMAGE=$value ;;
      SPAWNER_MEMORY_LIMIT) MEMORY_LIMIT=${MEMORY_LIMIT:-$value} ;;
      SPAWNER_SECRET) SECRET=$value ;;
      POSTGRES_PASSWORD) POSTGRES_PASSWORD=$value ;;
      SPAWNER_BOOTSTRAP_TOKEN) BOOTSTRAP_TOKEN=${BOOTSTRAP_TOKEN:-$value} ;;
    esac
  done <"$ENV_FILE"
  INSTALLED=true
  if [ -n "$previous_data_dir" ]; then
    [ -z "$DATA_DIR" ] || [ "$DATA_DIR" = "$previous_data_dir" ] ||
      die "the data of this installation is in $previous_data_dir, not $DATA_DIR: moving it is not supported"
    DATA_DIR=$previous_data_dir
  fi
  DATA_DIR=${DATA_DIR:-/var/lib/spawner}
  check_directory SPAWNER_DATA_DIR "$DATA_DIR"
}

# Refuses a directory the installer would write to, or delete with --purge,
# that is not one of its own: relative, with "..", or a directory of the
# system.
check_directory() {
  local name=$1 dir=$2
  [[ "$dir" == /* && "$dir" != *"/../"* && "$dir" != *"/.." && "$dir" != *"/./"* ]] || die "$name must be an absolute path without . or .., not \"$dir\""
  dir=${dir%/}
  case "${dir:-/}" in
    / | /bin | /boot | /dev | /etc | /home | /lib | /lib64 | /media | /mnt | /opt | /proc | /root | /run | /sbin | /srv | /sys | /tmp | /usr | /usr/* | /var | /var/lib | /var/log)
      die "$name cannot be $dir, a directory of the system: use a directory of its own, such as /var/lib/spawner"
      ;;
  esac
}

# --- Checks -------------------------------------------------------------------

# The system, the processor, the memory; for a new installation, the free
# disk and the ports too.
check_system() {
  local fresh=${1:-true}
  step "Checking the server"
  [ "$(id -u)" -eq 0 ] || die "run it as root: curl -fsSL https://github.com/Flosk6/Spawner/releases/latest/download/install.sh | sudo bash"

  [ -r /etc/os-release ] || die "unknown system: Ubuntu 22.04 or 24.04, or Debian 12, needed"
  local system
  system=$(os_release PRETTY_NAME)
  case "$(os_release ID)-$(os_release VERSION_ID)" in
    ubuntu-22.04 | ubuntu-24.04 | debian-12) ok "$system" ;;
    *)
      [ "${SPAWNER_SKIP_OS_CHECK:-}" = 1 ] || die "$system is not supported: Ubuntu 22.04 or 24.04, or Debian 12 (SPAWNER_SKIP_OS_CHECK=1 to try anyway)"
      warn "$system is not supported: going on"
      ;;
  esac

  case "$(uname -m)" in
    x86_64 | aarch64 | arm64) ok "$(uname -m)" ;;
    *) die "$(uname -m) is not supported: amd64 or arm64 needed" ;;
  esac

  MEMORY_GB=$(awk '/^MemTotal:/ { printf "%d", $2 / 1024 / 1024 + 0.5 }' /proc/meminfo)
  [ "$MEMORY_GB" -ge 2 ] || die "${MEMORY_GB} GiB of memory: 4 GiB needed, 8 advised"
  if [ "$MEMORY_GB" -lt 4 ]; then
    warn "$(small_memory)"
  elif [ "$MEMORY_GB" -lt 8 ]; then
    warn "${MEMORY_GB} GiB of memory: it runs, 8 GiB are advised for several environments at once"
  else
    ok "${MEMORY_GB} GiB of memory"
  fi

  [ "$fresh" = true ] || return 0
  mkdir -p "$(dirname "$DATA_DIR")"
  local free_gb
  free_gb=$(df -Pk "$(dirname "$DATA_DIR")" | awk 'NR == 2 { printf "%d", $4 / 1024 / 1024 }')
  [ "$free_gb" -ge "$MIN_DISK_GB" ] || die "${free_gb} GiB free on $(dirname "$DATA_DIR"): ${MIN_DISK_GB} GiB at least"
  ok "${free_gb} GiB of disk free"

  local port ports="80"
  [ "$TLS" = off ] || ports="80 443"
  for port in $ports; do
    if ss -Hltn "sport = :$port" 2>/dev/null | grep -q . && ! docker ps --format '{{.Names}}' 2>/dev/null | grep -qx spawner-traefik; then
      die "port $port is taken: Spawner's proxy needs it ($(ss -Hltnp "sport = :$port" 2>/dev/null | head -1 | awk '{print $NF}'))"
    fi
  done
  ok "ports $ports free"
}

# Below 4 GiB, the defaults leave no memory for a single environment: what to
# lower instead.
small_memory() {
  printf '%s GiB of memory: with the default settings, no environment starts below 4 GiB. Lower the memory of an environment (SPAWNER_ENV_MEMORY, 2g by default) and the memory a build waits for (MIN_REQUIRED_FREE_MEMORY_GB, 2 by default), on the Settings page of the dashboard or in %s. 8 GiB are advised' \
    "$MEMORY_GB" "$SETTINGS_FILE"
}

# --- Questions ----------------------------------------------------------------

ask_questions() {
  step "Configuration"
  if [ "$TLS" = off ]; then
    DOMAIN=${DOMAIN:-localtest.me}
    DNS_PROVIDER=none
    ok "local install over HTTP, on $DOMAIN"
    warn "plain HTTP on port 80 of every interface: whoever reaches this machine reaches the dashboard and the previews unencrypted. Keep it to a laptop or a private network."
    return
  fi
  if [ -z "$DOMAIN" ]; then
    say "Spawner serves each environment on <env>--<project>.<domain>, and its dashboard on spawner.<domain>."
    say "A DNS record *.<domain> (type A) must point to this server."
    ask DOMAIN "Domain of the previews, such as preview.example.com"
  fi
  [[ "$DOMAIN" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]] || die "\"$DOMAIN\" is not a domain name"
  [ -n "$EMAIL" ] || ask EMAIL "E-mail of the Let's Encrypt account"
  [[ "$EMAIL" == *@*.* ]] || die "\"$EMAIL\" is not an e-mail address"

  if [ -z "$DNS_PROVIDER" ]; then
    say ""
    say "With your DNS provider's API, Spawner gets one wildcard certificate for *.$DOMAIN."
    say "Without it, it gets one certificate per URL: Let's Encrypt allows about 50 a week."
    say "  1) Cloudflare   2) OVH   3) Hetzner   4) Scaleway   5) DigitalOcean"
    say "  6) Route 53     7) Gandi 8) another provider (lego code)   9) none"
    local choice
    ask choice "DNS provider" 9
    case "$choice" in
      1) DNS_PROVIDER=cloudflare ;;
      2) DNS_PROVIDER=ovh ;;
      3) DNS_PROVIDER=hetzner ;;
      4) DNS_PROVIDER=scaleway ;;
      5) DNS_PROVIDER=digitalocean ;;
      6) DNS_PROVIDER=route53 ;;
      7) DNS_PROVIDER=gandiv5 ;;
      8) ask DNS_PROVIDER "Code of the provider (https://go-acme.github.io/lego/dns/)" ;;
      *) DNS_PROVIDER=none ;;
    esac
  fi
  [ "$DNS_PROVIDER" = none ] || ask_dns_credentials
}

# Credentials of the DNS provider: --dns-env, the variables themselves, or
# questions. Traefik alone receives them (dns.env).
ask_dns_credentials() {
  local names=() name value entry
  case "$DNS_PROVIDER" in
    cloudflare) names=(CF_DNS_API_TOKEN) ;;
    ovh) names=(OVH_ENDPOINT OVH_APPLICATION_KEY OVH_APPLICATION_SECRET OVH_CONSUMER_KEY) ;;
    hetzner) names=(HETZNER_API_TOKEN) ;;
    scaleway) names=(SCW_SECRET_KEY) ;;
    digitalocean) names=(DO_AUTH_TOKEN) ;;
    route53) names=(AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION) ;;
    gandiv5) names=(GANDIV5_PERSONAL_ACCESS_TOKEN) ;;
  esac
  for entry in "${DNS_VARS[@]+"${DNS_VARS[@]}"}"; do
    [[ "$entry" == *=* ]] || die "--dns-env $entry: expected KEY=VALUE"
    DNS_VALUES[${entry%%=*}]=${entry#*=}
  done
  if [ -f "$DNS_ENV_FILE" ]; then
    local line
    while IFS= read -r line || [ -n "$line" ]; do
      [[ "$line" == *=* ]] || continue
      name=${line%%=*}
      value=${line#*=}
      [ -n "$name" ] && [ -z "${DNS_VALUES[$name]:-}" ] && DNS_VALUES[$name]=$value
    done <"$DNS_ENV_FILE"
  fi
  for name in "${names[@]+"${names[@]}"}"; do
    [ -z "${DNS_VALUES[$name]:-}" ] || continue
    value=${!name:-}
    if [ -z "$value" ] && [ "$name" = OVH_ENDPOINT ]; then
      ask value "$name (ovh-eu, ovh-ca, ovh-us)" ovh-eu
    elif [ -z "$value" ] && [ "$name" = AWS_REGION ]; then
      ask value "$name"
    elif [ -z "$value" ]; then
      ask_secret value "$name"
    fi
    DNS_VALUES[$name]=$value
  done
  if [ ${#names[@]} -eq 0 ] && [ ${#DNS_VALUES[@]} -eq 0 ]; then
    [ "$ASSUME_YES" != true ] && [ -r /dev/tty ] || die "--dns-provider $DNS_PROVIDER needs its credentials: --dns-env KEY=VALUE"
    say "Give the variables of $DNS_PROVIDER listed on https://go-acme.github.io/lego/dns/$DNS_PROVIDER/, one KEY=VALUE per line, then an empty line:"
    while read -rs entry </dev/tty && [ -n "$entry" ]; do
      if [[ "$entry" == *=* ]]; then
        DNS_VALUES[${entry%%=*}]=${entry#*=}
        say "${entry%%=*}=(hidden)"
      else
        warn "expected KEY=VALUE"
      fi
    done
    [ ${#DNS_VALUES[@]} -gt 0 ] || die "no credential for $DNS_PROVIDER"
  fi
  # The Hetzner DNS provider read HETZNER_API_KEY before Traefik's lego moved to HETZNER_API_TOKEN.
  if [ "$DNS_PROVIDER" = hetzner ] && [ -n "${DNS_VALUES[HETZNER_API_TOKEN]:-}" ]; then
    DNS_VALUES[HETZNER_API_KEY]=${DNS_VALUES[HETZNER_API_TOKEN]}
  fi
  ok "DNS provider $DNS_PROVIDER: ${!DNS_VALUES[*]}"
}

check_dns() {
  [ "$TLS" != off ] || return 0
  step "Checking the DNS"
  local public host ip
  public=$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)
  for host in "spawner.$DOMAIN" "check-$RANDOM.$DOMAIN"; do
    ip=$(getent ahostsv4 "$host" 2>/dev/null | awk 'NR == 1 { print $1 }')
    if [ -z "$ip" ]; then
      warn "$host does not resolve: create a DNS record *.$DOMAIN of type A pointing to ${public:-this server}, then wait for it to spread"
      return 0
    fi
    if [ -n "$public" ] && [ "$ip" != "$public" ]; then
      warn "$host resolves to $ip, not to this server ($public): certificates will fail until it does"
      return 0
    fi
  done
  ok "*.$DOMAIN points to this server${public:+ ($public)}"
}

# --- Docker -------------------------------------------------------------------

install_docker() {
  step "Docker"
  if ! command -v docker >/dev/null 2>&1; then
    say "Installing Docker from get.docker.com"
    curl -fsSL https://get.docker.com | sh >/dev/null
    DOCKER_INSTALLED_NOW=true
  fi
  docker compose version >/dev/null 2>&1 || die "the Docker Compose plugin is missing: apt-get install docker-compose-plugin with Docker's packages, or docker-compose-v2 with Ubuntu's docker.io"
  ok "$(docker --version), $(docker compose version --short 2>/dev/null || echo compose)"
  configure_docker
}

# Docker settings for many short-lived environments: compressed logs with a
# cap, a build cache with a limit, room for hundreds of networks, containers
# that survive a restart of Docker. On a new Docker, images are stored once
# (overlay2) rather than twice (containerd image store).
configure_docker() {
  local daemon=/etc/docker/daemon.json total_gb keep_gb wanted changed
  total_gb=$(df -Pk /var/lib | awk 'NR == 2 { printf "%d", $2 / 1024 / 1024 }')
  keep_gb=$((total_gb * 15 / 100))
  [ "$keep_gb" -le 20 ] || keep_gb=20
  [ "$keep_gb" -ge 5 ] || keep_gb=5
  wanted=$(
    cat <<EOF
{
  "log-driver": "local",
  "log-opts": { "max-size": "10m", "max-file": "3" },
  "builder": { "gc": { "enabled": true, "defaultKeepStorage": "${keep_gb}GB" } },
  "default-address-pools": [{ "base": "10.210.0.0/16", "size": 24 }],
  "live-restore": true$([ "$DOCKER_INSTALLED_NOW" = true ] && printf ',\n  "features": { "containerd-snapshotter": false }')
}
EOF
  )
  mkdir -p /etc/docker
  if [ ! -s "$daemon" ]; then
    printf '%s\n' "$wanted" >"$daemon"
    changed=true
  elif command -v python3 >/dev/null 2>&1; then
    changed=$(
      python3 - "$daemon" "$wanted" <<'PY'
import json, sys
path, wanted = sys.argv[1], json.loads(sys.argv[2])
current = json.load(open(path))
missing = {key: value for key, value in wanted.items() if key not in current and key != "features"}
if missing:
    current.update(missing)
    json.dump(current, open(path, "w"), indent=2)
print("true" if missing else "false")
PY
    )
  else
    warn "$daemon exists and python3 is missing: add these settings yourself if they are not there: $wanted"
    changed=false
  fi
  if [ "$changed" = true ]; then
    systemctl restart docker
    ok "Docker settings written to $daemon (logs capped, build cache kept under ${keep_gb} GB, networks /24)"
  else
    ok "Docker settings already in place"
  fi
}

configure_zram() {
  [ "$MEMORY_GB" -lt 8 ] || return 0
  if [ -z "$ZRAM" ]; then
    if confirm "Below 8 GiB of memory, compressed swap in memory (zram) keeps idle pages compressed. Enable it?" y; then ZRAM=yes; else ZRAM=no; fi
  fi
  [ "$ZRAM" = yes ] || return 0
  command -v apt-get >/dev/null 2>&1 || { warn "zram needs apt-get: skipped"; return 0; }
  step "zram"
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq zram-tools >/dev/null
  printf 'ALGO=zstd\nPERCENT=50\nPRIORITY=100\n' >/etc/default/zramswap
  systemctl restart zramswap
  ok "zram swap: half of the memory, zstd"
}

# --- Files and start ----------------------------------------------------------

# Whether version $1 comes before $2: 2.0.0-rc.1 before 2.0.0 before 2.0.1.
version_before() {
  local a=${1%%-*} b=${2%%-*}
  if [ "$a" != "$b" ]; then
    [ "$(printf '%s\n%s\n' "$a" "$b" | sort -V | head -1)" = "$a" ]
    return
  fi
  [[ "$1" == *-* ]] || return 1
  [[ "$2" != *-* ]] && return 0
  [ "$1" != "$2" ] && [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -1)" = "$1" ]
}

resolve_version() {
  if [ "$VERSION" = latest ]; then
    VERSION=$(curl -fsS --max-time 10 "$RELEASES_API" | grep -o '"tag_name": *"[^"]*"' | head -1 | sed 's/.*"v\{0,1\}\([^"]*\)"$/\1/')
    [ -n "$VERSION" ] || die "the latest release could not be found on GitHub: give --version"
  fi
  VERSION=${VERSION#v}
  if [ "$ACTION" = upgrade ]; then
    VERSION=${VERSION:-$DEFAULT_VERSION}
  else
    VERSION=${VERSION:-${PREVIOUS_VERSION:-$DEFAULT_VERSION}}
  fi
  if [ -n "${PREVIOUS_VERSION:-}" ] && [ "$ALLOW_DOWNGRADE" != true ] && version_before "$VERSION" "$PREVIOUS_VERSION"; then
    die "$VERSION is older than the installed $PREVIOUS_VERSION, whose database only migrates forward: restore a backup taken by $VERSION first, then --allow-downgrade (docs/operations.md)"
  fi
  if [ -z "$IMAGE" ]; then
    if [ -n "${PREVIOUS_IMAGE:-}" ] && [[ "$PREVIOUS_IMAGE" != "$IMAGE_REPOSITORY:"* ]] && [ "$ACTION" != upgrade ]; then
      IMAGE=$PREVIOUS_IMAGE
    else
      IMAGE="$IMAGE_REPOSITORY:$VERSION"
      [ -z "$IMAGE_DIGEST" ] || [ "$VERSION" != "$DEFAULT_VERSION" ] || IMAGE+="@$IMAGE_DIGEST"
    fi
  fi
}

write_files() {
  step "Writing $INSTALL_DIR"
  if [ "${INSTALLED:-false}" = true ] && { [ -z "${SECRET:-}" ] || [ -z "${POSTGRES_PASSWORD:-}" ]; }; then
    die "$ENV_FILE lacks SPAWNER_SECRET or POSTGRES_PASSWORD: put them back from a copy of it (docs/operations.md), new ones would lock the data out"
  fi
  mkdir -p "$INSTALL_DIR/backups" "$DATA_DIR"
  chmod 700 "$INSTALL_DIR" "$DATA_DIR"
  SECRET=${SECRET:-$(random_secret)}
  POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-$(random_secret)}
  MEMORY_LIMIT=${MEMORY_LIMIT:-1g}
  local wildcard=false
  [ "$TLS" = off ] || [ "$DNS_PROVIDER" = none ] || wildcard=true

  umask 077
  cat >"$ENV_FILE.new" <<EOF
$MARKER: rerun it to change these values.
SPAWNER_VERSION=$VERSION
SPAWNER_IMAGE=$IMAGE
SPAWNER_DATA_DIR=$DATA_DIR
SPAWNER_PREVIEW_DOMAIN=$DOMAIN
SPAWNER_TLS=${TLS:-letsencrypt}
SPAWNER_TLS_WILDCARD=$wildcard
SPAWNER_DNS_PROVIDER=$DNS_PROVIDER
ACME_EMAIL=$EMAIL
SPAWNER_SECRET=$SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
SPAWNER_BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN
SPAWNER_MEMORY_LIMIT=$MEMORY_LIMIT
EOF
  mv "$ENV_FILE.new" "$ENV_FILE"
  : >"$DNS_ENV_FILE.new"
  if [ "$wildcard" = true ]; then
    local name
    for name in "${!DNS_VALUES[@]}"; do
      printf '%s=%s\n' "$name" "${DNS_VALUES[$name]}" >>"$DNS_ENV_FILE.new"
    done
  fi
  mv "$DNS_ENV_FILE.new" "$DNS_ENV_FILE"
  if [ ! -f "$SETTINGS_FILE" ]; then
    cat >"$SETTINGS_FILE" <<'SETTINGS'
# Settings of your own for Spawner, one VARIABLE=value per line: the installer
# never overwrites this file. Most limits change from the dashboard (System,
# Settings); these are the others, for example:
#   SPAWNER_BUILD_CONCURRENCY=2          builds at once (default: 1 below 8 GiB of memory, 2 above)
#   SPAWNER_UPLOAD_MAX=200m              largest worktree upload, compressed (default: 100m)
#   SPAWNER_START_TIMEOUT_SECONDS=600    how long services may take to start (default: 300)
#   SESSION_MAX_AGE=604800000            dashboard sessions, in milliseconds (default: 24 hours)
# Apply a change: docker compose --project-directory /opt/spawner --env-file /opt/spawner/.env up -d
SETTINGS
  fi
  umask 022
  chmod 600 "$ENV_FILE" "$DNS_ENV_FILE" "$SETTINGS_FILE"

  # Every entry point drops the request headers whose name has a character
  # other than a letter, a digit or a dash (aliasheadersstrategy=delete):
  # PHP or CGI read X_Spawner_Preview or X.Forwarded.For as the dashed name,
  # which Traefik's middlewares remove or set.
  local scheme=https ports='      - "80:80"
      - "443:443"' traefik_tls=""
  if [ "$TLS" = off ]; then
    scheme=http
    ports='      - "80:80"'
  else
    # shellcheck disable=SC2016 # ${ACME_EMAIL} is for Compose, which reads it from .env
    traefik_tls='      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.aliasheadersstrategy=delete
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'
    if [ "$wildcard" = true ]; then
      traefik_tls+="
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=\${SPAWNER_DNS_PROVIDER}
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
    else
      traefik_tls+="
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    fi
  fi

  cat >"$COMPOSE_FILE" <<EOF
$MARKER (version $VERSION): rerun it rather than editing this file.
#
# Dashboard: $scheme://spawner.$DOMAIN
# Environments: $scheme://<env>--<project>.$DOMAIN
#
# The data directory is mounted at the same path in the Spawner container:
# the compose files Spawner renders use these paths.

name: spawner

services:
  postgres:
    image: $POSTGRES_IMAGE
    container_name: spawner-postgres
    restart: unless-stopped
    mem_limit: 1g
    environment:
      POSTGRES_DB: spawner
      POSTGRES_USER: spawner
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: [spawner-core]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spawner -d spawner"]
      interval: 5s
      timeout: 5s
      retries: 30

  traefik:
    image: $TRAEFIK_IMAGE
    container_name: spawner-traefik
    restart: unless-stopped
    mem_limit: 512m
    # Root in its container, for the certificates it already stored, but
    # without the capabilities of root: it binds ports, nothing else.
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    security_opt: [no-new-privileges:true]
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.aliasheadersstrategy=delete
$traefik_tls
      - --ping=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --log.level=WARN
    env_file: [dns.env]
    ports:
$ports
    volumes:
      - \${SPAWNER_DATA_DIR}/traefik:/etc/traefik/dynamic:ro
      - traefik-certs:/letsencrypt
    networks: [spawner-core]
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  # The rules of firewall.nft for the containers of Docker's bridge networks:
  # no cloud metadata, and of the host only DNS, HTTP and HTTPS. Loaded again
  # every minute, in case something flushed them.
  firewall:
    image: \${SPAWNER_IMAGE}
    container_name: spawner-firewall
    restart: unless-stopped
    network_mode: host
    user: "0"
    cap_drop: [ALL]
    cap_add: [NET_ADMIN]
    security_opt: [no-new-privileges:true]
    read_only: true
    entrypoint: ["/usr/bin/tini", "-g", "--"]
    command: ["sh", "-c", "while nft -f /app/firewall.nft; do sleep 60; done"]
    # Healthy while the rules are in place (the image's own check is the API's).
    healthcheck:
      test: ["CMD", "nft", "list", "table", "inet", "spawner"]
      interval: 10s
      timeout: 5s
      retries: 3

  spawner:
    image: \${SPAWNER_IMAGE}
    container_name: spawner
    restart: unless-stopped
    mem_limit: \${SPAWNER_MEMORY_LIMIT}
    depends_on:
      postgres: { condition: service_healthy }
    env_file: [spawner.env]
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://spawner:\${POSTGRES_PASSWORD}@postgres:5432/spawner
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: spawner
      DB_PASSWORD: \${POSTGRES_PASSWORD}
      DB_NAME: spawner
      SPAWNER_DATA_DIR: \${SPAWNER_DATA_DIR}
      SPAWNER_PREVIEW_DOMAIN: \${SPAWNER_PREVIEW_DOMAIN}
      SPAWNER_TLS: \${SPAWNER_TLS}
      SPAWNER_TLS_WILDCARD: \${SPAWNER_TLS_WILDCARD}
      SPAWNER_SECRET: \${SPAWNER_SECRET}
      SPAWNER_BOOTSTRAP_TOKEN: \${SPAWNER_BOOTSTRAP_TOKEN}
      SPAWNER_TRAEFIK_CONTAINER: spawner-traefik
      SPAWNER_DASHBOARD_UPSTREAM: http://spawner.spawner-core:3000
      DOCKER_SOCKET: /var/run/docker.sock
    volumes:
      - \${SPAWNER_DATA_DIR}:\${SPAWNER_DATA_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [spawner-core]

networks:
  spawner-core:
    name: spawner-core

volumes:
  postgres-data:
  traefik-certs:
EOF
  ok "compose.yaml, .env, dns.env and spawner.env (readable by root only)"
}

compose() {
  docker compose --project-directory "$INSTALL_DIR" -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

start() {
  step "Starting Spawner $VERSION"
  if [[ "$IMAGE" == "$IMAGE_REPOSITORY:"* ]] || ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    compose pull --quiet ||
      die "the images could not be downloaded: does version $VERSION exist (https://github.com/Flosk6/Spawner/releases), and is $IMAGE_REPOSITORY public?"
  else
    compose pull --quiet postgres traefik
  fi
  configure_firewall
  STARTED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  REPLACED=true
  compose up -d --remove-orphans
  wait_healthy
  wait_served
}

# Copies the rules of the image to firewall.nft, and has Docker load them
# before it starts any container (a drop-in of docker.service): after a
# reboot, the environments would otherwise run a moment before the
# spawner-firewall container. An update from the dashboard runs this
# installer in a container, without systemd: the file is refreshed for the
# drop-in an earlier run on the host wrote.
configure_firewall() {
  docker run --rm --entrypoint cat "$IMAGE" /app/firewall.nft >"$FIREWALL_FILE.new" || die "the rules of $IMAGE could not be read"
  mv "$FIREWALL_FILE.new" "$FIREWALL_FILE"
  chmod 644 "$FIREWALL_FILE"
  if [ ! -d /run/systemd/system ]; then
    [ -f "$FIREWALL_DROPIN" ] || say "The rules for the environments load once the stack runs; run the installer on the server (--upgrade) to load them before Docker at boot."
    return 0
  fi
  if ! command -v nft >/dev/null 2>&1; then
    command -v apt-get >/dev/null 2>&1 || { warn "nft is missing: the rules for the environments load once the stack runs, not before Docker at boot"; return 0; }
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables >/dev/null 2>&1 ||
      { apt-get update -qq >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nftables >/dev/null; }
  fi
  mkdir -p "$(dirname "$FIREWALL_DROPIN")"
  cat >"$FIREWALL_DROPIN" <<EOF
$MARKER: the rules of $FIREWALL_FILE for the containers
# of Docker's bridge networks, loaded before Docker starts any of them.
[Service]
ExecStartPre=-$(command -v nft) -f $FIREWALL_FILE
EOF
  systemctl daemon-reload
  ok "firewall.nft: containers reach neither the cloud's metadata nor the host's other services, from boot on"
}

# Waits up to 3 minutes for Spawner to report healthy; gives up as soon as it
# keeps restarting.
wait_for_spawner() {
  local status="" restarts
  for _ in $(seq 1 90); do
    status=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' spawner 2>/dev/null || true)
    [ "$status" = healthy ] && return 0
    restarts=$(docker inspect -f '{{.RestartCount}}' spawner 2>/dev/null || echo 0)
    [ "${restarts:-0}" -lt 3 ] || return 1
    sleep 2
  done
  return 1
}

wait_healthy() {
  if wait_for_spawner; then
    ok "Spawner is up"
    return 0
  fi
  docker logs --tail 40 spawner >&2 || true
  die "Spawner did not start: its last logs are above"
}

# Waits until Traefik serves the dashboard, with a certificate over HTTPS.
wait_served() {
  if [ "$TLS" = off ]; then
    for _ in $(seq 1 30); do
      curl -fsS -o /dev/null --max-time 5 -H "Host: spawner.$DOMAIN" "http://127.0.0.1/api/v1/healthz" && { ok "the dashboard answers on http://spawner.$DOMAIN"; return 0; }
      sleep 2
    done
    die "Traefik does not serve the dashboard: docker logs spawner-traefik"
  fi
  say "Waiting for the certificate (up to 3 minutes)"
  for _ in $(seq 1 90); do
    curl -fsS -o /dev/null --max-time 5 --resolve "spawner.$DOMAIN:443:127.0.0.1" "https://spawner.$DOMAIN/api/v1/healthz" 2>/dev/null &&
      { ok "the dashboard answers on https://spawner.$DOMAIN with its certificate"; return 0; }
    sleep 2
  done
  warn "no certificate yet for spawner.$DOMAIN: check the DNS record *.$DOMAIN, then docker logs spawner-traefik. Let's Encrypt retries by itself."
}

summary() {
  local scheme=https invite
  [ "$TLS" = off ] && scheme=http
  invite=$(docker logs --since "$STARTED_AT" spawner 2>&1 | grep -o 'https\{0,1\}://[^ ]*/invite/[A-Za-z0-9_-]*' | tail -1 || true)
  step "Spawner $VERSION is running"
  say "  Dashboard     $scheme://spawner.$DOMAIN"
  if [ -n "$invite" ]; then
    say "  First admin   $invite"
    say "                ${DIM}valid one hour; a new one: docker exec -u node spawner node dist/admin.js invite --role admin${RESET}"
  fi
  say ""
  say "On your machine, install the CLI and log in:"
  say "  npm install -g spawner-cli    ${DIM}# or: curl -fsSL $scheme://spawner.$DOMAIN/api/v1/cli/spawner -o ~/.local/bin/spawner && chmod +x ~/.local/bin/spawner${RESET}"
  say "  spawner login $scheme://spawner.$DOMAIN"
  say ""
  say "Files in $INSTALL_DIR, data in $DATA_DIR. Upgrade: rerun this installer with --upgrade."
  [ "${MEMORY_GB:-8}" -ge 4 ] || warn "$(small_memory)"
}

# --- Upgrade and removal ------------------------------------------------------

# Saves the database before an upgrade. Postgres is started for it when it
# was stopped: an upgrade never goes on without a backup.
backup_database() {
  if ! docker ps --format '{{.Names}}' | grep -qx spawner-postgres; then
    [ -f "$COMPOSE_FILE" ] || die "Postgres is not running and $COMPOSE_FILE is missing: the database cannot be backed up before the upgrade"
    say "Starting Postgres to back the database up"
    compose up -d postgres >/dev/null 2>&1 || die "Postgres does not start: the database cannot be backed up before the upgrade (docker logs spawner-postgres)"
    local ready=false
    for _ in $(seq 1 30); do
      docker exec spawner-postgres pg_isready -U spawner -d spawner >/dev/null 2>&1 && { ready=true; break; }
      sleep 2
    done
    [ "$ready" = true ] || die "Postgres does not answer: the database cannot be backed up before the upgrade (docker logs spawner-postgres)"
  fi
  local file
  file="$INSTALL_DIR/backups/spawner-$(date -u +%Y%m%d-%H%M%S)-${PREVIOUS_VERSION:-unknown}.sql.gz"
  docker exec spawner-postgres pg_dump -U spawner -d spawner | gzip >"$file"
  chmod 600 "$file"
  BACKUP_FILE=$file
  ok "database saved to $file"
  local backups
  mapfile -t backups < <(find "$INSTALL_DIR/backups" -maxdepth 1 -name 'spawner-*.sql.gz' | sort)
  [ "${#backups[@]}" -le "$BACKUPS_KEPT" ] || rm -f "${backups[@]:0:${#backups[@]}-BACKUPS_KEPT}"
}

upgrade() {
  [ -f "$ENV_FILE" ] || die "Spawner is not installed in $INSTALL_DIR: run the installer without --upgrade"
  [ -f "$COMPOSE_FILE" ] || die "$COMPOSE_FILE is missing: run the installer without --upgrade, which writes it again"
  check_system false
  resolve_version
  step "Upgrading from ${PREVIOUS_VERSION:-an unknown version} to $VERSION"
  backup_database
  [ "$DNS_PROVIDER" = none ] || [ "$TLS" = off ] || ask_dns_credentials
  cp -p "$ENV_FILE" "$ENV_FILE.previous"
  cp -p "$COMPOSE_FILE" "$COMPOSE_FILE.previous"
  ROLLBACK=true
  write_files
  start
  ROLLBACK=false
  rm -f "$ENV_FILE.previous" "$COMPOSE_FILE.previous"
  summary
}

# Puts the previous version back after a failed upgrade: its files and, when
# the new version already ran (it may have migrated the database), the
# database as the backup holds it.
roll_back() {
  ROLLBACK=false
  step "Going back to ${PREVIOUS_VERSION:-the previous version}"
  cp -p "$ENV_FILE.previous" "$ENV_FILE"
  cp -p "$COMPOSE_FILE.previous" "$COMPOSE_FILE"
  rm -f "$ENV_FILE.previous" "$COMPOSE_FILE.previous"
  if [ "$REPLACED" != true ]; then
    ok "nothing was changed: Spawner ${PREVIOUS_VERSION:-} still runs"
    return 0
  fi
  compose stop spawner >/dev/null 2>&1 || true
  if [ -n "$BACKUP_FILE" ]; then
    if docker exec spawner-postgres psql -q -U spawner -d postgres -c 'DROP DATABASE spawner WITH (FORCE)' -c 'CREATE DATABASE spawner' >/dev/null &&
      gunzip -c "$BACKUP_FILE" | docker exec -i spawner-postgres psql -q -U spawner -d spawner >/dev/null; then
      ok "database restored from $BACKUP_FILE"
    else
      warn "the database could not be restored: restore $BACKUP_FILE by hand (https://spawner.run/docs/operations/#restoring)"
    fi
  fi
  compose up -d --remove-orphans >/dev/null 2>&1 || true
  if wait_for_spawner; then
    ok "Spawner ${PREVIOUS_VERSION:-} runs again"
  else
    warn "the previous version does not start either: docker logs spawner"
  fi
}

uninstall() {
  [ "$(id -u)" -eq 0 ] || die "run it as root"
  if [ "$PURGE" = true ]; then
    say "This deletes Spawner, every environment it runs with their data, its database, $DATA_DIR, and $INSTALL_DIR with the backups of the database and the secrets."
    if [ "$ASSUME_YES" != true ]; then
      local answer=""
      [ -r /dev/tty ] || die "confirm with --yes"
      read -r -p 'Type "delete everything" to go on: ' answer </dev/tty || true
      [ "$answer" = "delete everything" ] || die "nothing was deleted"
    fi
  else
    confirm "Stop Spawner and its environments? Their data stays: rerun the installer to start again." y || die "nothing was stopped"
  fi
  step "Stopping Spawner"
  docker rm -f spawner-upgrade >/dev/null 2>&1 || true
  local down=(down)
  [ "$PURGE" = false ] || down+=(--volumes)
  [ ! -f "$COMPOSE_FILE" ] || compose "${down[@]}" || true
  local ids
  mapfile -t ids < <(docker ps -aq --filter label=dev.spawner.env)
  if [ "$PURGE" = true ]; then
    [ "${#ids[@]}" -eq 0 ] || docker rm -f -v "${ids[@]}" >/dev/null
    mapfile -t ids < <(docker volume ls -q --filter label=dev.spawner.env)
    [ "${#ids[@]}" -eq 0 ] || docker volume rm "${ids[@]}" >/dev/null
    mapfile -t ids < <(docker network ls -q --filter label=dev.spawner.env)
    [ "${#ids[@]}" -eq 0 ] || docker network rm "${ids[@]}" >/dev/null
    mapfile -t ids < <(docker images -q --filter label=dev.spawner.env | sort -u)
    [ "${#ids[@]}" -eq 0 ] || docker rmi -f "${ids[@]}" >/dev/null 2>&1 || true
    if [ -f "$FIREWALL_DROPIN" ]; then
      rm -f "$FIREWALL_DROPIN"
      systemctl daemon-reload
    fi
    ! command -v nft >/dev/null 2>&1 || nft delete table inet spawner 2>/dev/null || true
    rm -rf "$DATA_DIR" "$INSTALL_DIR"
    ok "Spawner, its environments and its data are deleted"
  else
    [ "${#ids[@]}" -eq 0 ] || docker stop "${ids[@]}" >/dev/null
    ok "Spawner and its environments are stopped; the data stays in $DATA_DIR and $INSTALL_DIR"
  fi
}

# --- Main ---------------------------------------------------------------------

main() {
  parse_args "$@"
  check_directory SPAWNER_INSTALL_DIR "$INSTALL_DIR"
  case "$ACTION" in
    uninstall)
      load_previous
      uninstall
      return
      ;;
    upgrade)
      load_previous
      upgrade
      return
      ;;
  esac
  load_previous
  TLS=${TLS:-letsencrypt}
  check_system
  ask_questions
  check_dns
  install_docker
  configure_zram
  resolve_version
  [ -z "${PREVIOUS_VERSION:-}" ] || backup_database
  write_files
  start
  summary
}

main "$@"
