baseDomain: "localhost"

resources:
  # Simple Node.js API example (has Dockerfile)
  - name: "simple-api"
    type: "laravel-api"
    gitRepo: "https://github.com/docker/getting-started-app.git"
    defaultBranch: "main"
    dbResource: "simple-db"

  # Simple Next.js example repo
  - name: "simple-front"
    type: "nextjs-front"
    gitRepo: "https://github.com/vercel/next-learn.git"
    defaultBranch: "main"
    apiResource: "simple-api"

  - name: "simple-db"
    type: "mysql-db"
