<template>
  <div
    class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 overflow-y-auto"
    @click="$emit('close')"
  >
    <div
      class="bg-white rounded-lg p-6 max-w-2xl w-full my-8"
      @click.stop
    >
      <h2 class="text-2xl font-bold text-gray-800 mb-6">
        {{ isEdit ? 'Edit Resource' : 'Add Resource' }}
      </h2>

      <div class="space-y-4">
        <!-- Name -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Resource Name <span class="text-red-500">*</span>
          </label>
          <input
            v-model="form.name"
            type="text"
            placeholder="iris-api"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <!-- Type -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Resource Type <span class="text-red-500">*</span>
          </label>
          <select
            v-model="form.type"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option value="mysql-db">MySQL Database</option>
            <option value="laravel-api">Laravel API</option>
            <option value="nextjs-front">Next.js Frontend</option>
          </select>
        </div>

        <!-- Git Repo (for laravel-api and nextjs-front) -->
        <div v-if="form.type !== 'mysql-db'">
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Git Repository <span class="text-red-500">*</span>
          </label>
          <input
            v-model="form.gitRepo"
            type="text"
            placeholder="git@github.com:org/repo.git"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <!-- Default Branch -->
        <div v-if="form.type !== 'mysql-db'">
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Default Branch <span class="text-red-500">*</span>
          </label>
          <input
            v-model="form.defaultBranch"
            type="text"
            placeholder="main"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <!-- DB Resource (for laravel-api) -->
        <div v-if="form.type === 'laravel-api'">
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Database Resource <span class="text-red-500">*</span>
          </label>
          <select
            v-model="form.dbResourceId"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option :value="null">Select a database</option>
            <option
              v-for="db in databaseResources"
              :key="db.id"
              :value="db.id"
            >
              {{ db.name }}
            </option>
          </select>
        </div>

        <!-- API Resource (for nextjs-front) -->
        <div v-if="form.type === 'nextjs-front'">
          <label class="block text-sm font-medium text-gray-700 mb-1">
            API Resource <span class="text-red-500">*</span>
          </label>
          <select
            v-model="form.apiResourceId"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option :value="null">Select an API</option>
            <option
              v-for="api in apiResources"
              :key="api.id"
              :value="api.id"
            >
              {{ api.name }}
            </option>
          </select>
        </div>

        <!-- Static Environment Variables -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Static Environment Variables
          </label>
          <p class="text-xs text-gray-500 mb-2">
            Paste your environment variables here (KEY=value format, one per line).
            Variables like DB_HOST, DB_PASSWORD, APP_URL will be auto-generated by Spawner.
          </p>
          <textarea
            v-model="form.staticEnvVars"
            rows="10"
            placeholder="APP_NAME=Iris API
ROLLBAR_TOKEN=your_token_here
MAIL_FROM_ADDRESS=noreply@example.com
SENDGRID_API_KEY=SG.xxx

# Auto-generated by Spawner (no need to add):
# DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD
# APP_KEY, APP_URL
# NEXT_PUBLIC_API_URL, NODE_ENV"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
          ></textarea>
        </div>

        <!-- Post-Build Commands -->
        <div v-if="form.type !== 'mysql-db'">
          <label class="block text-sm font-medium text-gray-700 mb-1">
            Post-Build Commands
          </label>
          <p class="text-xs text-gray-500 mb-2">
            Commands to run after containers start (one per line). Example: migrations, seeds, cache warm-up.
          </p>
          <textarea
            v-model="postBuildCommandsText"
            rows="4"
            placeholder="php artisan migrate --force
php artisan db:seed --force"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent font-mono text-sm"
          ></textarea>
        </div>
      </div>

      <div class="flex gap-3 mt-6">
        <button
          @click="$emit('close')"
          class="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-700 px-4 py-2 rounded-lg font-medium transition"
        >
          Cancel
        </button>
        <button
          @click="save"
          :disabled="saving"
          class="flex-1 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition disabled:opacity-50"
        >
          {{ saving ? 'Saving...' : (isEdit ? 'Update' : 'Add Resource') }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import axios from 'axios';

const props = defineProps({
  projectId: {
    type: Number,
    required: true,
  },
  resource: {
    type: Object,
    default: null,
  },
  allResources: {
    type: Array,
    default: () => [],
  },
});

const emit = defineEmits(['close', 'saved']);

const isEdit = computed(() => !!props.resource);

const form = ref({
  name: '',
  type: 'mysql-db',
  gitRepo: '',
  defaultBranch: 'main',
  dbResourceId: null,
  apiResourceId: null,
  staticEnvVars: '',
});

const postBuildCommandsText = ref('');
const saving = ref(false);

const databaseResources = computed(() => {
  return props.allResources.filter(r => r.type === 'mysql-db');
});

const apiResources = computed(() => {
  return props.allResources.filter(r => r.type === 'laravel-api');
});

function initForm() {
  if (props.resource) {
    form.value = {
      name: props.resource.name || '',
      type: props.resource.type || 'mysql-db',
      gitRepo: props.resource.gitRepo || '',
      defaultBranch: props.resource.defaultBranch || 'main',
      dbResourceId: props.resource.dbResourceId || null,
      apiResourceId: props.resource.apiResourceId || null,
      staticEnvVars: stringifyEnvVars(props.resource.staticEnvVars || {}),
    };

    // Load post-build commands
    postBuildCommandsText.value = (props.resource.postBuildCommands || []).join('\n');
  }
}

function stringifyEnvVars(vars) {
  return Object.entries(vars)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
}

async function save() {
  // Validation
  if (!form.value.name) {
    alert('Please enter a resource name');
    return;
  }

  if (form.value.type !== 'mysql-db') {
    if (!form.value.gitRepo || !form.value.defaultBranch) {
      alert('Please fill in Git repository and default branch');
      return;
    }
  }

  if (form.value.type === 'laravel-api' && !form.value.dbResourceId) {
    alert('Please select a database resource');
    return;
  }

  if (form.value.type === 'nextjs-front' && !form.value.apiResourceId) {
    alert('Please select an API resource');
    return;
  }

  try {
    saving.value = true;

    // Convert post-build commands text to array
    const postBuildCommands = postBuildCommandsText.value
      .split('\n')
      .map(cmd => cmd.trim())
      .filter(cmd => cmd.length > 0 && !cmd.startsWith('#'));

    const payload = {
      name: form.value.name,
      type: form.value.type,
      gitRepo: form.value.gitRepo || null,
      defaultBranch: form.value.defaultBranch || null,
      dbResourceId: form.value.dbResourceId || null,
      apiResourceId: form.value.apiResourceId || null,
      staticEnvVars: form.value.staticEnvVars, // Send as string, backend will parse it
      postBuildCommands: postBuildCommands,
    };

    if (isEdit.value) {
      await axios.put(
        `/api/projects/${props.projectId}/resources/${props.resource.id}`,
        payload
      );
    } else {
      await axios.post(`/api/projects/${props.projectId}/resources`, payload);
    }

    emit('saved');
  } catch (error) {
    console.error('Error saving resource:', error);
    alert(error.response?.data?.message || 'Failed to save resource');
  } finally {
    saving.value = false;
  }
}

onMounted(() => {
  initForm();
});
</script>
