/**
 * Service to parse environment variables from text format (KEY=value)
 * Filters out auto-generated variables that Spawner will create
 */
export class EnvVarsParser {
  private static AUTO_GENERATED_KEYS = [
    // Only these are truly auto-generated by Spawner
    'APP_KEY',      // Laravel: requires special base64 format
    'NODE_ENV',     // Next.js: always set to 'production'
  ];

  /**
   * Parse environment variables from text format
   * @param envText - Text in format "KEY=value\nKEY2=value2"
   * @returns Object with parsed variables (excluding auto-generated ones)
   */
  static parse(envText: string): Record<string, string> {
    const vars: Record<string, string> = {};

    if (!envText || envText.trim() === '') {
      return vars;
    }

    const lines = envText.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }

      // Match KEY=value pattern
      const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
      if (match) {
        const [, key, value] = match;

        // Skip auto-generated variables
        if (this.AUTO_GENERATED_KEYS.includes(key)) {
          continue;
        }

        vars[key] = value;
      }
    }

    return vars;
  }

  /**
   * Convert object back to text format for display
   * @param vars - Object with environment variables
   * @returns Text in format "KEY=value\nKEY2=value2"
   */
  static stringify(vars: Record<string, string>): string {
    return Object.entries(vars)
      .map(([key, value]) => `${key}=${value}`)
      .join('\n');
  }
}
